config/routes.rb
Blazer::Engine.routes.draw do
  resources :queries do
    post :run, on: :collection # err on the side of caution
    post :cancel, on: :collection
    post :refresh, on: :member
    get :tables, on: :collection
    get :schema, on: :collection
    get :docs, on: :collection
    get :like, on: :member
    get :dislike, on: :member
  end

  resources :checks, except: [:show] do
    get :run, on: :member
  end

  resources :dashboards, except: [:index] do
    post :refresh, on: :member
  end

  if Blazer.uploads?
    resources :uploads do
    end
  end

  resources :categories do
  end

  root to: "queries#home"
end

app/models/blazer/audit.rb
module Blazer
  class Audit < Record
    belongs_to :user, optional: true, class_name: Blazer.user_class.to_s
    belongs_to :query, optional: true
  end
end

app/models/blazer/category.rb
module Blazer
  class Category < Record
    has_many :queries
  end
end

app/models/blazer/check.rb
module Blazer
  class Check < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    belongs_to :query

    validates :query_id, presence: true
    validate :validate_emails
    validate :validate_variables, if: -> { query_id_changed? }

    before_validation :set_state
    before_validation :fix_emails

    def split_emails
      emails.to_s.downcase.split(",").map(&:strip)
    end

    def split_slack_channels
      if Blazer.slack?
        slack_channels.to_s.downcase.split(",").map(&:strip)
      else
        []
      end
    end

    def update_state(result)
      check_type =
        if respond_to?(:check_type)
          self.check_type
        elsif respond_to?(:invert)
          invert ? "missing_data" : "bad_data"
        else
          "bad_data"
        end

      message = result.error

      self.state =
        if result.timed_out?
          "timed out"
        elsif result.error
          "error"
        elsif check_type == "anomaly"
          anomaly, message = result.detect_anomaly
          if anomaly.nil?
            "error"
          elsif anomaly
            "failing"
          else
            "passing"
          end
        elsif result.rows.any?
          check_type == "missing_data" ? "passing" : "failing"
        else
          check_type == "missing_data" ? "failing" : "passing"
        end

      self.last_run_at = Time.now if respond_to?(:last_run_at=)
      self.message = message if respond_to?(:message=)

      if respond_to?(:timeouts=)
        if result.timed_out?
          self.timeouts += 1
          self.state = "disabled" if timeouts >= 3
        else
          self.timeouts = 0
        end
      end

      # do not notify on creation, except when not passing
      if (state_was != "new" || state != "passing") && state != state_was
        Blazer::CheckMailer.state_change(self, state, state_was, result.rows.size, message, result.columns, result.rows.first(10).as_json, result.column_types, check_type).deliver_now if emails.present?
        Blazer::SlackNotifier.state_change(self, state, state_was, result.rows.size, message, check_type)
      end
      save! if changed?
    end

    private

      def set_state
        self.state ||= "new"
      end

      def fix_emails
        # some people like doing ; instead of ,
        # but we know what they mean, so let's fix it
        # also, some people like to use whitespace
        if emails.present?
          self.emails = emails.strip.gsub(/[;\s]/, ",").gsub(/,+/, ", ")
        end
      end

      def validate_emails
        unless split_emails.all? { |e| e =~ /\A\S+@\S+\.\S+\z/ }
          errors.add(:base, "Invalid emails")
        end
      end

      def validate_variables
        if query.variables.any?
          errors.add(:base, "Query can't have variables")
        end
      end
  end
end

app/models/blazer/connection.rb
module Blazer
  class Connection < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blazer/dashboard.rb
module Blazer
  class Dashboard < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    has_many :dashboard_queries, dependent: :destroy
    has_many :queries, through: :dashboard_queries

    validates :name, presence: true

    def variables
      queries.flat_map { |q| q.variables }.uniq
    end

    def to_param
      [id, name.gsub("'", "").parameterize].join("-")
    end
  end
end

app/models/blazer/dashboard_query.rb
module Blazer
  class DashboardQuery < Record
    belongs_to :dashboard
    belongs_to :query

    validates :dashboard_id, presence: true
    validates :query_id, presence: true
  end
end

app/models/blazer/like.rb
module Blazer
  class Like < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    belongs_to :query
  end
end

app/models/blazer/record.rb
module Blazer
  class Record < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blazer/uploads_connection.rb
module Blazer
  class UploadsConnection < ActiveRecord::Base
    self.abstract_class = true

    establish_connection Blazer.settings["uploads"]["url"] if Blazer.uploads?
  end
end

app/controllers/blazer/base_controller.rb
module Blazer
  class BaseController < ApplicationController
    # skip filters
    filters = _process_action_callbacks.map(&:filter) - [:activate_authlogic]
    skip_before_action(*filters, raise: false)
    skip_after_action(*filters, raise: false)
    skip_around_action(*filters, raise: false)

    clear_helpers

    protect_from_forgery with: :exception

    if ENV["BLAZER_PASSWORD"]
      http_basic_authenticate_with name: ENV["BLAZER_USERNAME"], password: ENV["BLAZER_PASSWORD"]
    end

    if Blazer.settings["before_action"]
      raise Blazer::Error, "The docs for protecting Blazer with a custom before_action had an incorrect example from August 2017 to June 2018. The example method had a boolean return value. However, you must render or redirect if a user is unauthorized rather than return a falsy value. Double check that your before_action works correctly for unauthorized users (if it worked when added, there should be no issue). Then, change before_action to before_action_method in config/blazer.yml."
    end

    if Blazer.before_action
      before_action Blazer.before_action.to_sym
    end

    if Blazer.override_csp
      after_action do
        response.headers['Content-Security-Policy'] = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data:"
      end
    end

    layout "blazer/application"

    private

      def process_vars(statement, var_params = nil)
        var_params ||= request.query_parameters
        (@bind_vars ||= []).concat(statement.variables).uniq!
        # update in-place so populated in view and consistent across queries on dashboard
        @bind_vars.each do |var|
          if !var_params[var]
            default = statement.data_source.variable_defaults[var]
            # only add if default exists
            var_params[var] = default if default
          end
        end
        runnable = @bind_vars.all? { |v| var_params[v] }
        statement.add_values(var_params) if runnable
        runnable
      end

      def refresh_query(query)
        statement = query.statement_object
        runnable = process_vars(statement)
        cohort_analysis_statement(statement) if statement.cohort_analysis?
        statement.clear_cache if runnable
      end

      def add_cohort_analysis_vars
        @bind_vars << "cohort_period" unless @bind_vars.include?("cohort_period")
        @smart_vars["cohort_period"] = ["day", "week", "month"] if @smart_vars
        # TODO create var_params method
        request.query_parameters["cohort_period"] ||= "week"
      end

      def parse_smart_variables(var, data_source)
        smart_var_data_source =
          ([data_source] + Array(data_source.settings["inherit_smart_settings"]).map { |ds| Blazer.data_sources[ds] }).find { |ds| ds.smart_variables[var] }

        if smart_var_data_source
          query = smart_var_data_source.smart_variables[var]

          if query.is_a? Hash
            smart_var = query.map { |k,v| [v, k] }
          elsif query.is_a? Array
            smart_var = query.map { |v| [v, v] }
          elsif query
            result = smart_var_data_source.run_statement(query)
            smart_var = result.rows.map { |v| v.reverse }
            error = result.error if result.error
          end
        end

        [smart_var, error]
      end

      def cohort_analysis_statement(statement)
        @cohort_period = params["cohort_period"] || "week"
        @cohort_period = "week" unless ["day", "week", "month"].include?(@cohort_period)

        # for now
        @conversion_period = @cohort_period
        @cohort_days =
          case @cohort_period
          when "day"
            1
          when "week"
            7
          when "month"
            30
          end

        statement.apply_cohort_analysis(period: @cohort_period, days: @cohort_days)
      end

      # TODO allow all keys
      # or show error message for disallowed keys
      UNPERMITTED_KEYS = [:controller, :action, :id, :host, :query, :dashboard, :query_id, :query_ids, :table_names, :authenticity_token, :utf8, :_method, :commit, :statement, :data_source, :name, :fork_query_id, :blazer, :run_id, :script_name, :original_script_name]

      def variable_params(resource, var_params = nil)
        permitted_keys = resource.variables - UNPERMITTED_KEYS.map(&:to_s)
        var_params ||= request.query_parameters
        var_params.slice(*permitted_keys)
      end
      helper_method :variable_params

      def blazer_user
        send(Blazer.user_method) if Blazer.user_method && respond_to?(Blazer.user_method, true)
      end
      helper_method :blazer_user

      def is_category_admin
        return true if Blazer.user_roles.nil? || Blazer.user_roles_data_source.nil? || Blazer.category_admin_role_ids.nil?
        data_source = Blazer.data_sources[Blazer.user_roles_data_source]
        result = data_source.run_statement(ActiveRecord::Base.send(:sanitize_sql_array, [Blazer.user_roles.sub("{id}", "(?)"), blazer_user[:id]]))
        roles = result.rows.map { |i| i.first }
        roles.intersection(Blazer.category_admin_role_ids).count > 0
      end
      helper_method :is_category_admin

      def render_errors(resource)
        @errors = resource.errors
        action = resource.persisted? ? :edit : :new
        render action, status: :unprocessable_entity
      end

      # do not inherit from ApplicationController - #120
      def default_url_options
        {}
      end
  end
end

app/controllers/blazer/categories_controller.rb
module Blazer
  class CategoriesController < BaseController
    before_action :check_is_category_admin

    def index
      @categories = Blazer::Category.all.order(:name)
    end

    def show
      @category = Blazer::Category.find(params[:id])
    end

    def new
      @category = Blazer::Category.new
    end

    def create
      @category = Blazer::Category.new(category_params)

      if @category.save
        redirect_to_list
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @category = Blazer::Category.find(params[:id])
    end

    def update
      @category = Blazer::Category.find(params[:id])

      if @category.update(category_params)
        redirect_to_list
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @category = Blazer::Category.find(params[:id])
      Blazer::Query.where('category_id = ?', params[:id]).update_all(category_id: nil)
      @category.destroy

      redirect_to_list
    end

    def redirect_to_list
      redirect_to action: "index"
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end

    def check_is_category_admin
      render_forbidden if !is_category_admin
    end

    def render_forbidden
      render plain: "Access denied", status: :forbidden
    end
  end
end

app/controllers/blazer/checks_controller.rb
module Blazer
  class ChecksController < BaseController
    before_action :set_check, only: [:edit, :update, :destroy, :run]

    def index
      state_order = [nil, "disabled", "error", "timed out", "failing", "passing"]
      @checks = Blazer::Check.joins(:query).includes(:query).order("blazer_queries.name, blazer_checks.id").to_a.sort_by { |q| state_order.index(q.state) || 99 }
      @checks.select! { |c| "#{c.query.name} #{c.emails}".downcase.include?(params[:q]) } if params[:q]
    end

    def new
      @check = Blazer::Check.new(query_id: params[:query_id])
    end

    def create
      @check = Blazer::Check.new(check_params)
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @check.creator = blazer_user if @check.respond_to?(:creator_id=) && blazer_user

      if @check.save
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def update
      if @check.update(check_params)
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def destroy
      @check.destroy
      redirect_to checks_path
    end

    def run
      @query = @check.query
      redirect_to query_path(@query)
    end

    private

      def check_params
        params.require(:check).permit(:query_id, :emails, :slack_channels, :invert, :check_type, :schedule)
      end

      def set_check
        @check = Blazer::Check.find(params[:id])
      end
  end
end

app/controllers/blazer/dashboards_controller.rb
module Blazer
  class DashboardsController < BaseController
    before_action :set_dashboard, only: [:show, :edit, :update, :destroy, :refresh]

    def new
      @dashboard = Blazer::Dashboard.new
    end

    def create
      @dashboard = Blazer::Dashboard.new
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @dashboard.creator = blazer_user if @dashboard.respond_to?(:creator_id=) && blazer_user

      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard)
      else
        render_errors @dashboard
      end
    end

    def show
      @queries = @dashboard.dashboard_queries.order(:position).preload(:query).map(&:query)
      @queries.each do |query|
        @success = process_vars(query.statement_object)
      end
      @bind_vars ||= []

      @smart_vars = {}
      @sql_errors = []
      @data_sources = @queries.map { |q| Blazer.data_sources[q.data_source] }.uniq
      @bind_vars.each do |var|
        @data_sources.each do |data_source|
          smart_var, error = parse_smart_variables(var, data_source)
          ((@smart_vars[var] ||= []).concat(smart_var)).uniq! if smart_var
          @sql_errors << error if error
        end
      end

      add_cohort_analysis_vars if @queries.any?(&:cohort_analysis?)
    end

    def edit
    end

    def update
      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard, params: variable_params(@dashboard))
      else
        render_errors @dashboard
      end
    end

    def destroy
      @dashboard.destroy
      redirect_to root_path
    end

    def refresh
      @dashboard.queries.each do |query|
        refresh_query(query)
      end
      redirect_to dashboard_path(@dashboard, params: variable_params(@dashboard))
    end

    private

      def dashboard_params
        params.require(:dashboard).permit(:name)
      end

      def set_dashboard
        @dashboard = Blazer::Dashboard.find(params[:id])
      end

      def update_dashboard(dashboard)
        dashboard.assign_attributes(dashboard_params)
        Blazer::Dashboard.transaction do
          if params[:query_ids].is_a?(Array)
            query_ids = params[:query_ids].map(&:to_i)
            @queries = Blazer::Query.find(query_ids).sort_by { |q| query_ids.index(q.id) }
          end
          if dashboard.save
            if @queries
              @queries.each_with_index do |query, i|
                dashboard_query = dashboard.dashboard_queries.where(query_id: query.id).first_or_initialize
                dashboard_query.position = i
                dashboard_query.save!
              end
              if dashboard.persisted?
                dashboard.dashboard_queries.where.not(query_id: query_ids).destroy_all
              end
            end
            true
          end
        end
      end
  end
end

app/helpers/blazer/base_helper.rb
module Blazer
  module BaseHelper
    def blazer_title(title = nil)
      if title
        content_for(:title) { title }
      else
        content_for?(:title) ? content_for(:title) : nil
      end
    end

    BLAZER_URL_REGEX = /\Ahttps?:\/\/[\S]+\z/
    BLAZER_IMAGE_EXT = %w[png jpg jpeg gif]

    def blazer_format_value(key, value)
      if value.is_a?(Numeric) && !key.to_s.end_with?("id") && !key.to_s.start_with?("id")
        number_with_delimiter(value)
      elsif value.is_a?(String) && value =~ BLAZER_URL_REGEX
        # see if image or link
        if Blazer.images && (key.include?("image") || BLAZER_IMAGE_EXT.include?(value.split(".").last.split("?").first.try(:downcase)))
          link_to value, target: "_blank" do
            image_tag value, referrerpolicy: "no-referrer"
          end
        else
          link_to value, value, target: "_blank"
        end
      else
        value
      end
    end

    def blazer_maps?
      Blazer.mapbox_access_token.present?
    end

    def blazer_js_var(name, value)
      "var #{name} = #{json_escape(value.to_json(root: false))};".html_safe
    end

    def blazer_series_name(k)
      k.nil? ? "null" : k.to_s
    end
  end
end

app/views/blazer/queries/_caching.html.erb
<% if @cached_at || @just_cached %>
  <p class="text-muted" style="float: right;">
    <% if @cached_at %>
      Cached <%= time_ago_in_words(@cached_at, include_seconds: true) %> ago
    <% elsif params[:query_id] %>
      Cached just now
      <% if @data_source.cache_mode == "slow" %>
        (over <%= "%g" % @data_source.cache_slow_threshold %>s)
      <% end %>
    <% end %>

    <% if @query && params[:query_id] %>
      <%= link_to "Refresh", refresh_query_path(@query, params: variable_params(@query, @var_params)), method: :post %>
    <% end %>
  </p>
<% end %>

app/views/blazer/queries/edit.html.erb
<% blazer_title "Edit - #{@query.name}" %>
<%= render partial: "form" %>

app/views/blazer/queries/home.html.erb
<div id="queries">
  <div id="header">
    <div class="pull-right" style="line-height: 34px;">
      <% if blazer_user %>
        <%= link_to "All", root_path, class: !params[:filter] ? "active" : nil, style: "margin-right: 40px;" %>

        <%= link_to "Liked", root_path(filter: "liked"), class: params[:filter] == "liked" ? "active" : nil, style: "margin-right: 40px;" %>

        <%= link_to "Mine", root_path(filter: "mine"), class: params[:filter] == "mine" ? "active" : nil, style: "margin-right: 40px;" %>
      <% end %>

      <div class="btn-group">
        <%= link_to "New Query", new_query_path, class: "btn btn-info" %>
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Checks", checks_path %></li>
          <% if Blazer.uploads? %>
            <li><%= link_to "Uploads", uploads_path %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Dashboard", new_dashboard_path %></li>
          <li><%= link_to "New Check", new_check_path %></li>
        </ul>
      </div>
      <% if is_category_admin %>
        <div class="btn-group">
          <%= link_to 'Categories', categories_path, class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
    <input type="text" v-model="searchTerm" placeholder="Start typing a category, query, dashboard, or person" style="width: 300px; display: inline-block;" v-focus class="search form-control" />
  </div>

  <table class="table">
    <thead>
      <tr>
        <th style="width: 20%">Category</th>
        <th>Name</th>
        <th style="width: 10%; text-align: right;">Likes</th>
        <th style="width: 10%; text-align: right;">Viewed</th>
        <th style="width: 20%; text-align: right;">Created At</th>
        <% if Blazer.user_class %>
          <th style="width: 20%; text-align: right;">Mastermind</th>
        <% end%>
      </tr>
    </thead>
    <tbody class="list" v-cloak>
      <tr v-for="query in visibleItems">
        <td v-if="query.category_id !== null">
          {{ query.category_name }}
        </td>
        <td v-if="query.category_id === null">
        </td>
        <td>
          <% if blazer_user %>
            <a v-if="query.liked" v-on:click="like($event, query, false)"><i class="fa fa-thumbs-up" aria-hidden="true" style="color:#337ab7"></i></a>
            <a v-else v-on:click="like($event, query)"><i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:#337ab7"></i></a>
          <% end %>
          <a :href="itemPath(query)" :class="{ dashboard: query.dashboard }">{{ query.name }}</a>
          <span class="vars">{{ query.vars }}</span>
        </td>
        <td class="creator">
          {{ query.likes_count }}
        </td>
        <td class="creator">
          {{ query.viewed_count }}
        </td>
        <td class="creator">
          {{ query.created_at }}
        </td>
        <% if Blazer.user_class %>
          <td class="creator">{{ query.creator }}</td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <p v-if="more" class="text-muted">Loading...</p>
</div>

<script>
  <%= blazer_js_var "dashboards", @dashboards %>
  <%= blazer_js_var "queries", @queries %>
  <%= blazer_js_var "more", @more %>

  var prepareSearch = function (list) {
    var i, q, searchStr
    for (i = 0; i < list.length; i++) {
      q = list[i]
      searchStr = q.name + q.creator + q.category_name
      if (q.creator === "You") {
        searchStr += "mine me"
      }
      q.searchStr = prepareQuery(searchStr)
    }
  }

  var prepareQuery = function (str) {
    return str.toLowerCase()
  }

  var app = new Vue({
    el: "#queries",
    data: {
      searchTerm: "",
      more: more,
      updateCounter: 0
    },
    created: function() {
      this.listItems = dashboards.concat(queries)

      prepareSearch(this.listItems)

      this.queryIds = {}
      for (i = 0; i < queries.length; i++) {
        this.queryIds[queries[i].id] = true
      }

      if (this.more) {
        var _this = this

        $.getJSON(Routes.queries_path(), function (data) {
          var i, j, newValues, val, size = 500;

          var newValues = []
          for (j = 0; j < data.length; j++) {
            val = data[j]
            if (val && !_this.queryIds[val.id]) {
              newValues.push(val)
            }
          }

          prepareSearch(newValues)

          _this.listItems = _this.listItems.concat(newValues)
          _this.more = false
          // hack to get to update
          _this.updateCounter++
        })
      }
    },
    computed: {
      visibleItems: function () {
        // hack to get to update
        this.updateCounter
        var q, i

        if (this.searchTerm.length > 0) {
          var term = prepareQuery(this.searchTerm)
          var items = []
          var fuzzyItems = []
          for (i = 0; i < this.listItems.length; i++) {
            q = this.listItems[i]
            if (q.searchStr.indexOf(term) !== -1) {
              items.push(q)
            } else if (fuzzysearch(term, q.searchStr)) {
              fuzzyItems.push(q)
            }
          }
          return items.concat(fuzzyItems)
        } else {
          return this.listItems
        }
      }
    },
    methods: {
      itemPath: function (item) {
        if (item.dashboard) {
          return Routes.dashboard_path(item.to_param)
        } else {
          return Routes.query_path(item.to_param)
        }
      },
      like: function(event, item, like = true) {
        event.target.classList.remove(...event.target.classList);
        event.target.classList.add(..."fa fa-spinner fa-spin".split(" "));
        window.location.href = like ? Routes.like_path(item.to_param) : Routes.dislike_path(item.to_param)
      }
    },
    directives: {
      focus: {
        inserted: function (el) {
          el.focus()
        }
      }
    }
  })
</script>

app/views/blazer/queries/new.html.erb
<% blazer_title "New Query" %>
<%= render partial: "form" %>

app/views/blazer/queries/show.html.erb
<% blazer_title @query.name %>

<% if @success %>
  <% run_data = {statement: @query.statement, query_id: @query.id, data_source: @query.data_source, variables: variable_params(@query)} %>
  <% run_data.merge!(forecast: "t") if params[:forecast] %>
  <% run_data.merge!(cohort_period: params[:cohort_period]) if params[:cohort_period] %>
  <% run_data.transform_keys!(&:to_s) if Rails::VERSION::STRING.to_f == 5.0 %>
<% end %>

<style>
    .hidden {
        visibility: hidden;
    }
</style>

<div class="topbar">
  <div class="container">
    <div class="row" style="padding-top: 13px;">
      <div class="col-sm-9">
        <%= render partial: "blazer/nav" %>
        <h3 style="line-height: 34px; display: inline; margin-left: 5px;">
          <%= @query.name %>
        </h3>
        <h1 style="line-height: 34px; display: inline; margin-left: 5px; font-size: 15px">
          <%= @query.category_name %>
        </h1>
      </div>
      <div class="col-sm-3 text-right">
        <%= link_to "Edit", edit_query_path(@query, params: variable_params(@query)), class: "btn btn-default", disabled: !@query.editable?(blazer_user) %>
        <%= link_to "Fork", new_query_path(params: variable_params(@query).merge(fork_query_id: @query.id, data_source: @query.data_source, name: @query.name)), class: "btn btn-info" %>

        <% if !@error && @success %>
            <%= button_to "Download", run_queries_path(format: "csv"), params: run_data, class: "hidden", :form => { :id => "form_csv" } %>
            <%= button_to "Download xls", run_queries_path(format: "xls"), params: run_data, class: "hidden", :form => { :id => "form_xls" } %>
            <div class="btn-group">
              <%= link_to 'Download', "#", onclick: "$('#form_xls').submit()", class: "btn btn-success" %>
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "#", onclick: "$('#form_csv').submit()", class: "btn" do %>
                      <span class="glyphicon glyphicon-floppy-save"></span> Csv
                  <% end %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to "#", onclick: "$('#form_xls').submit()", class: "btn" do %>
                      <span class="glyphicon glyphicon-th-large"></span> Excel
                  <% end %>
                </li>
              </ul>
            </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div style="margin-bottom: 60px;"></div>

<% if @sql_errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @sql_errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @query.description.present? %>
  <p><%= @query.description %></p>
<% end %>

<%= render partial: "blazer/variables", locals: {action: query_path(@query)} %>

<pre id="code"><code><%= @statement.display_statement %></code></pre>

<% if @success %>
  <div id="results">
    <p class="text-muted">Loading...</p>
  </div>

  <script>
    function showRun(data) {
      $("#results").html(data)
      $("#results table").stupidtable(stupidtableCustomSettings).stickyTableHeaders({fixedOffset: 60})
    }

    function showError(message) {
      $("#results").addClass("query-error").html(message)
    }

    <%= blazer_js_var "data", run_data %>

    runQuery(data, showRun, showError)
  </script>
<% end %>

<% unless %w(mongodb).include?(Blazer.data_sources[@query.data_source].adapter) %>
  <script>
    // do not highlight really long queries
    // this can lead to performance issues
    if ($("code").text().length < 10000) {
      hljs.highlightBlock(document.getElementById("code"));
    }
  </script>
<% end %>